name: Update Spotify Status

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  update-spotify:
    runs-on: ubuntu-latest
    steps:
      - name: Get Spotify Current Track
        run: |
          # Replace with your own script or command to fetch and update the current track
          export CURRENT_TRACK=$(curl -X GET "https://api.spotify.com/v1/me/player/currently-playing" -H "Authorization: Bearer $SPOTIFY_TOKEN")
          echo "CURRENT_TRACK=$CURRENT_TRACK" >> $GITHUB_ENV
      - name: Update Badge
        run: |
          echo "Listening to $CURRENT_TRACK" > track.txt
          git add track.txt
          git commit -m "Updated Spotify status"
          git push
